openapi: 3.0.3

info:
  title: Eclipse Kapua REST API - Credential
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/credentials:
    get:
      tags:
        - Credential
      summary: Get all the Credentials
      operationId: credentialList
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - name: userId
          in: query
          description: The optional id to filter results
          schema:
            $ref: '../openapi.yaml#/components/schemas/kapuaId'
        - $ref: '../openapi.yaml#/components/parameters/limit'
        - $ref: '../openapi.yaml#/components/parameters/offset'

      responses:
        200:
          description: The list of the Credentials available in the Scope
          content:
            application/json:
              schema:
                $ref: './credential.yaml#/components/schemas/credentialListResult'
              example:
                type: credentialListResult
                limitExceeded: false
                size: 2
                items:
                  - id: LgJHjS2jvdE
                    scopeId: AQ
                    createdOn: "2023-03-09T13:58:30.385Z"
                    createdBy: AQ
                    modifiedOn: "2023-03-09T13:58:30.385Z"
                    modifiedBy: AQ
                    optlock: 0
                    userId: AQ
                    credentialType: PASSWORD
                    status: ENABLED
                    expirationDate: "2023-04-09T13:58:30.385Z"
                    loginFailures: 0
                    firstLoginFailure: "2023-03-09T13:58:30.385Z"
                    loginFailuresReset: "2023-03-10T13:58:30.385Z"
                    lockoutReset: "2023-03-09T14:58:30.385Z"
                  - id: LgREjS2jadE
                    scopeId: AQ
                    createdOn: "2023-03-09T13:58:30.385Z"
                    createdBy: AQ
                    modifiedOn: "2023-03-09T13:58:30.385Z"
                    modifiedBy: AQ
                    optlock: 0
                    userId: AQ
                    credentialType: API_KEY
                    status: ENABLED
                    expirationDate: "2023-04-09T13:58:30.385Z"
                    loginFailures: 0
                    firstLoginFailure: "2023-03-09T13:58:30.385Z"
                    loginFailuresReset: "2023-03-10T13:58:30.385Z"
                    lockoutReset: "2023-03-09T14:58:30.385Z"
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
    post:
      tags:
        - Credential
      summary: Create a new Credential
      operationId: credentialCreate
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
      requestBody:
        description: An object containing the properties for the new Credential to be created
        content:
          application/json:
            schema:
              $ref: './credential.yaml#/components/schemas/credentialCreator'
            examples:
              password:
                description: Password
                value:
                    userId: "AQ"
                    credentialType: PASSWORD
                    credentialKey: "New-password-123!"
                    credentialStatus: ENABLED
                    expirationDate: "2019-12-31T00:00:00.000Z"
              apikey:
                description: API Key
                value:
                  userId: "AQ"
                  credentialType: API_KEY
                  credentialStatus: ENABLED
                  expirationDate: "2019-12-31T00:00:00.000Z"
        required: true
      responses:
        201:
          description: The Credential that has just been created
          content:
            application/json:
              schema:
                $ref: './credential.yaml#/components/schemas/credential'
              examples:
                Password:
                  value:
                    id: LgJHjS2jvdE
                    scopeId: AQ
                    createdOn: "2023-03-09T13:58:30.385Z"
                    createdBy: AQ
                    modifiedOn: "2023-03-09T13:58:30.385Z"
                    modifiedBy: AQ
                    optlock: 0
                    userId: AQ
                    credentialType: PASSWORD
                    status: ENABLED
                    expirationDate: "2023-04-09T13:58:30.385Z"
                    loginFailures: 0
                    firstLoginFailure: "2023-03-09T13:58:30.385Z"
                    loginFailuresReset: "2023-03-10T13:58:30.385Z"
                    lockoutReset: "2023-03-09T14:58:30.385Z"
                API Key:
                  value:
                    id: LgJHjS2jvdE
                    scopeId: AQ
                    createdOn: "2023-03-09T13:58:30.385Z"
                    createdBy: AQ
                    modifiedOn: "2023-03-09T13:58:30.385Z"
                    modifiedBy: AQ
                    credentialKey: $2a$12$BjLeC/gqcnEyk.XNo2qorul.a/v4HDuOUlfmojdSZXRSFTjymPdVm
                    optlock: 0
                    userId: AQ
                    credentialType: PASSWORD
                    status: ENABLED
                    expirationDate: "2023-04-09T13:58:30.385Z"
                    loginFailures: 0
                    firstLoginFailure: "2023-03-09T13:58:30.385Z"
                    loginFailuresReset: "2023-03-10T13:58:30.385Z"
                    lockoutReset: "2023-03-09T14:58:30.385Z"
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
