openapi: 3.0.3

info:
  title: Everyware Cloud REST API - User Profile
  version: '1.0'
  contact:
    name: Eurotech
    url: https://www.eurotech.com

paths:

  /{scopeId}/user/profile/:
    get:
      tags:
        - User Profile
      summary: Get the User Profile
      operationId: userProfileGet
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
      responses:
        200:
          description: The desired user profile
          content:
            application/json:
              schema:
                $ref: './userProfile.yaml#/components/schemas/userProfile'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
    put:
      tags:
        - User Profile
      summary: Change the User Profile
      operationId: userProfileUpdate
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../openapi.yaml#/components/schemas/userProfile'
      responses:
        200:
          description: The user profile has been updated
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
      description: Change logged user profile